# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_client:
        scoped_clients:
            user_service.client:
                base_uri: 'http://user_service_nginx'
                timeout: 30
            product_service.client:
                base_uri: 'http://product_service_nginx'
                timeout: 30
            order_service.client:
                base_uri: 'http://order_service_nginx'
                timeout: 30

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
